### ISSUE TITLE
Build in Cygwin

### ISSUE THREAD

**Issue by ruv** [ikysil/ikforth#45]
Hi! How to build ikforth in Cygwin environment?

Running `scons` from the project root directory produces the key error:  `KeyError: 'HSYS'` in file `SConstruct`, line 7.

**Comment by ikysil** [comment]
Which targets you are interested in? Linux or Win32?

**Comment by ikysil** [comment]
Actual error:

```
$ scons
scons: Reading SConscript files ...
KeyError: 'HSYS':
  File "/home/user/workshop/ikysil/ikforth/SConstruct", line 7:
    exports = ['env'])
  File "/usr/lib/scons-2.4.0/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons-2.4.0/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/user/workshop/ikysil/ikforth/SConstruct-config", line 23:
    env.SetDefault(TSYS = env['HSYS'])
  File "/usr/lib/scons-2.4.0/SCons/Environment.py", line 410:
    return self._dict[key]

```

**Comment by ruv** [comment]
> Which targets you are interested in? Linux or Win32?

I supposed that the target should be Cygwin — Windows binaries (and ABI) and Linux API. Though, to get such result a Cygwin toolchain should be used. But it seems **flat assembler** is not the case:
> since the fasm assembler is, itself, written in fasm, you are at a sort of "chicken and the egg" case here.
> 
> The only solution I can see, if you want fasm to work from within cygwin, is to port the fasm sourcecode to gas syntax, and then assemble the fasm executable from gas. Then you may proceed to code using fasm under cygwin. 

([ShortCoder, 2004](https://board.flatassembler.net/topic.php?p=14339#14339))

Well, getting Win32 target on Cygwin is good enough too.

**Comment by ikysil** [comment]
Actually, FASM for Windows is usable under Cygwin.
I managed to build IKForth with the attached patches.
Console integration is not working though - it looks like Window's Console API is not implemented by Cygwin - see #46 for details.

The binary is usable under cmd.exe and WSL/bash consoles.

**Comment by ruv** [comment]
Yes, FASM for Windows is usable in the Cygwin terminal as most of other native Windows console applications.

Cygwin allows to compile a POSIX compatible application without changing its source code and to run it in Windows. So, the application can "think" that it is running in Linux, when it is actually running in Windows. But a Cygwin toolchain should be used for compiling. Theoretically FASM for Windows can be used to build such application too, but it will require a lot of additional code.

Regarding Cygwin terminal — I have answered in the thread #46.

**Comment by ruv** [comment]
Just for information: when `IKForth.exe` is build by `mingw32-g++.exe` (that is used in case of Cygwin), it requires `libgcc_s_dw2-1.dll` to run.
