### ISSUE TITLE
High CPU consumption while waiting for user's input in WIN-ACCEPT

### ISSUE THREAD

**Issue by ikysil** [ikysil/ikforth#46]
Root cause - call to `ReadConsoleInput` in `WIN-CONSOLE-EKEY` fails with 
```
ERROR_INVALID_FUNCTION

1 (0x1)

Incorrect function.
```

Both Cygwin and Git-Bash (MSYS) consoles are affected.

Seems to be working fine in CMD or WSL console window.

**Comment by ruv** [comment]
When a Windows console application is running under Cygwin terminal (mintty), it is running with stdio redirection to pipes, and a console window is not created. So, ReadConsoleInput returns error 0x6 ERROR_INVALID_HANDLE in such case.

It is useful if a Forth system is able to work with redirected stdio, regardless Cygwin terminals.


Regarding Bash shell. It can be started from mintty — and `ReadConsoleInput` will not work in child console applications; or from Windows console (e.g. regular instance of cmd.exe) — and `ReadConsoleInput` will work in child console applications.

**Comment by ikysil** [comment]
Repair for high CPU consumption has been confirmed using release [v20.03-RC5](../releases/tag/v20.03-RC5)
